"""Score the CpABC1 decoy panel with SPRINT, and apply the pass criterion.

SPRINT (https://github.com/abhinadduri/panspecies-dti, arXiv 2411.15418, MLSB 2024)
co-embeds a protein and a ligand into a shared space so that scoring a pair is one cosine
similarity. It embeds proteins with SaProt, which takes a *structure-aware* sequence:
residue letters interleaved with per-residue structure tokens from foldseek. That is more
information than PSICHIC had, which only ever saw the bare sequence.

The prediction going in, recorded so it cannot be quietly revised afterwards: SPRINT is the
same paradigm as PSICHIC, a co-embedding trained on bioactivity tables (PubChem 98%,
BindingDB, ChEMBL), so it is likely to fail the same way. The structure tokens are the
reason it is still worth running, along with the fact that scoring is nearly free.

## Why the protein gets cut, and how

SaProt here takes at most 1024 tokens, so at most 1022 residues. CpABC1 is 1431. Something
has to go, and *which* third is discarded is a real scientific choice:

  * `default` - what SPRINT does on its own. `SaProtFeaturizer.prepare_string` slices the
    interleaved string to `max_len*2-2` characters, keeping **residues 1-1023**. That is
    blind to the biology: it spends 348 residues on an N-terminal region that has nothing
    to do with the site, and still loses pocket residue 1101.
  * `pocket` - an informed cut. The 25 residues within 5 A of silybin in
    `cpabc1_silymarin.pdb` span 349-1101, only 753 residues, so a 1022-residue window
    centred on them (**residues 214-1235**) holds the entire binding site with ~135
    residues of flanking context on each side.

Both are run, because the comparison is informative either way. If the informed cut scores
better, the default truncation was hurting it; if both fail the panel, that is a stronger
negative result than either alone.

The SaProt string is always generated by foldseek on the *complete* structure and only then
sliced, so the structure tokens reflect each residue's real structural environment rather
than one recomputed from a chopped-up PDB.

Caveat to carry into any conclusion: either cut removes a nucleotide-binding domain, which
matters for how an ABC transporter works even when the pocket itself is intact.

Run with the `sprint` env, from the repo root:

    /opt/homebrew/Cellar/micromamba/2.9.0/envs/sprint/bin/python sandbox/sprint_decoy_test.py
"""

import math
import os
import resource
import subprocess
import sys
import time

import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SPRINT_DIR = os.path.join(REPO, "tools", "SPRINT")
WORK = os.path.join(HERE, "work")
RECEPTOR = os.path.join(REPO, "projects", "blue", "data", "cpabc1_receptor.pdb")
COMPLEX = os.path.join(REPO, "projects", "blue", "data", "cpabc1_silymarin.pdb")
# The Lit-PCBA checkpoint from tools/SPRINT/checkpoints/README.md
CHECKPOINT = os.path.join(WORK, "sprint.ckpt")
CHECKPOINT_GDRIVE_ID = "1uojdSn1otFKi-DBJyTKoOA6OZbwOQX6U"

N_RESIDUES = 1431          # CpABC1, UniProt Q9XYH6
TOKEN_BUDGET = 1022        # SaProt's 1024 tokens, less <cls> and <eos>
POCKET_CUTOFF = 5.0        # angstroms from any silybin heavy atom

AMINO = {"ALA", "ARG", "ASN", "ASP", "CYS", "GLN", "GLU", "GLY", "HIS", "ILE", "LEU",
         "LYS", "MET", "PHE", "PRO", "SER", "THR", "TRP", "TYR", "VAL"}

sys.path.insert(0, HERE)
from scoring_panel import evaluate, load_panel, report  # noqa: E402


def peak_gb():
    peak = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    return peak / 1024**3 if sys.platform == "darwin" else peak / 1024**2


def run(cmd, **kw):
    print("  $", " ".join(str(c) for c in cmd))
    # This interpreter is invoked by absolute path, so the env's bin/ is not on PATH and
    # child processes cannot find foldseek or the ultrafast-* entry points.
    env = dict(os.environ)
    env["PATH"] = os.path.dirname(sys.executable) + os.pathsep + env.get("PATH", "")
    subprocess.run(cmd, check=True, env=env, **kw)


def pocket_residues():
    """Residue numbers within POCKET_CUTOFF of any silybin heavy atom."""
    ligand, protein = [], {}
    with open(COMPLEX) as f:
        for line in f:
            if not line.startswith(("ATOM", "HETATM")):
                continue
            element = (line[76:78].strip() or line[12:16].strip()[:1])
            if element == "H":
                continue
            try:
                xyz = (float(line[30:38]), float(line[38:46]), float(line[46:54]))
            except ValueError:
                continue
            if line.startswith("HETATM") or line[17:20].strip() not in AMINO:
                ligand.append(xyz)
            else:
                protein.setdefault(int(line[22:26]), []).append(xyz)
    if not ligand:
        raise SystemExit(f"no ligand atoms found in {COMPLEX}")
    return sorted(r for r, atoms in protein.items()
                  if any(math.dist(a, l) <= POCKET_CUTOFF for a in atoms for l in ligand))


def pocket_window(pocket):
    """A TOKEN_BUDGET-residue window centred on the pocket, clamped to the sequence."""
    lo, hi = min(pocket), max(pocket)
    if hi - lo + 1 > TOKEN_BUDGET:
        raise SystemExit(f"pocket spans {hi - lo + 1} residues, over the "
                         f"{TOKEN_BUDGET}-residue budget; a contiguous cut cannot hold it")
    start = max(1, (lo + hi) // 2 - TOKEN_BUDGET // 2)
    end = start + TOKEN_BUDGET - 1
    if end > N_RESIDUES:
        end, start = N_RESIDUES, N_RESIDUES - TOKEN_BUDGET + 1
    return start, end


def slice_saprot(seq, start, end):
    """Residues start..end (1-based, inclusive) of an interleaved SaProt string."""
    return seq[2 * (start - 1):2 * end]


def saprot_sequence():
    """Structure-aware sequence for all of CpABC1 chain A, via foldseek.

    The receptor PDB comes out of Schrodinger Maestro and its B-factor column is all
    zeros, so `--no-plddt-mask` is required; with the mask on, every residue would look
    like it had pLDDT 0 and be discarded.
    """
    out_csv = os.path.join(WORK, "cpabc1_saprot.csv")
    if os.path.exists(out_csv):
        os.remove(out_csv)  # the script appends, so a stale file would accumulate rows
    run([sys.executable, os.path.join(SPRINT_DIR, "utils", "structure_to_saprot.py"),
         "-I", RECEPTOR, "-C", "A", "-O", out_csv, "--no-plddt-mask"])
    df = pd.read_csv(out_csv)
    col = "Target Sequence" if "Target Sequence" in df.columns else df.columns[-1]
    seq = str(df[col].iloc[0])

    # The uppercase half must be the sequence verified against UniProt Q9XYH6. If foldseek
    # dropped or reordered residues, every slice below would be off by an unknown amount.
    residues = "".join(c for c in seq if c.isupper())
    print(f"  SaProt string {len(seq)} chars -> {len(residues)} residues")
    if len(residues) != N_RESIDUES:
        raise SystemExit(f"expected {N_RESIDUES} residues for Q9XYH6, "
                         f"foldseek gave {len(residues)}")
    return seq


def _allow_full_unpickle():
    """Let the SPRINT checkpoint load under torch >= 2.6.

    SPRINT pins torch 2.4.1, where `torch.load` defaulted to `weights_only=False`. From
    2.6 the default is True and the Lightning checkpoint fails on its LeakyReLU object.
    Lightning passes `weights_only` explicitly, so it has to be overridden rather than
    defaulted. This permits arbitrary code execution on load, which is acceptable only
    because the file is the authors' own checkpoint, linked from
    tools/SPRINT/checkpoints/README.md and downloaded here by its Drive ID.
    """
    import torch

    if getattr(torch.load, "_sprint_patched", False):
        return
    original = torch.load

    def patched(*args, **kwargs):
        kwargs["weights_only"] = False
        return original(*args, **kwargs)

    patched._sprint_patched = True
    torch.load = patched


def load_model():
    """The trained SPRINT co-embedding model, on CPU and in eval mode."""
    _allow_full_unpickle()
    from ultrafast.model import DrugTargetCoembeddingLightning

    model = DrugTargetCoembeddingLightning.load_from_checkpoint(
        CHECKPOINT, map_location="cpu")
    model.eval()
    return model


def embed_drugs(model, smiles):
    """Morgan fingerprints through the model's drug projector.

    SPRINT's own `ultrafast-embed` path is bypassed. Its `EmbedDataset` caches features to
    disk and, with `ext="pt"`, `Featurizer.preload` blind-loads that cache instead of
    re-deriving per sequence, which fed single SMILES characters to RDKit and produced
    per-character feature matrices. Calling the projectors directly mirrors
    `DrugTargetCoembeddingLightning.forward` exactly and keeps the mapping from compound
    to vector under our control.

    Fingerprint settings match `MorganFeaturizer.smiles_to_morgan`: canonicalise, then
    radius 2 over 2048 bits.
    """
    import torch
    from rdkit import Chem, DataStructs
    from rdkit.Chem import rdFingerprintGenerator

    # `ultrafast.utils.canonicalize` is two lines and importing it hits a circular import
    # between ultrafast.utils and ultrafast.featurizers, so it is reproduced here exactly:
    # MolFromSmiles then MolToSmiles(isomericSmiles=True).
    def canonicalize(smi):
        mol = Chem.MolFromSmiles(smi)
        return Chem.MolToSmiles(mol, isomericSmiles=True) if mol is not None else None

    gen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)
    fps = []
    for smi in smiles:
        canonical = canonicalize(smi)
        mol = Chem.MolFromSmiles(canonical) if canonical else None
        if mol is None:
            raise SystemExit(f"RDKit rejected {smi!r}; the panel is validated, so this "
                             "means canonicalisation mangled it")
        arr = np.zeros((2048,), dtype=np.float32)
        DataStructs.ConvertToNumpyArray(gen.GetFingerprint(mol), arr)
        fps.append(arr)
    x = torch.from_numpy(np.stack(fps))
    with torch.no_grad():
        return model.drug_projector(x).numpy()


def embed_target(model, saprot_seq):
    """A structure-aware sequence through SaProt and the model's target projector.

    Mirrors `SaProtFeaturizer._transform_single`: tokenise, take layer-33 per-residue
    representations, drop <cls>/<eos>. `prepare_string` is deliberately not called - it
    would blind-truncate, and the string handed in here is already cut to the intended
    window and carries its own 3Di structure tokens.
    """
    import torch

    from ultrafast.saprot_utils import load_esm_saprot

    saprot, alphabet = load_esm_saprot(os.path.join(REPO, "tools", "SaProt_650M_AF2.pt"))
    saprot.eval()
    batch_converter = alphabet.get_batch_converter()
    _, _, tokens = batch_converter([("protein", saprot_seq)])
    with torch.no_grad():
        out = saprot(tokens, repr_layers=[33], return_contacts=False)
        per_residue = out["representations"][33][:, 1:tokens.shape[1] - 1, :]
        if per_residue.shape[1] != len(saprot_seq) // 2:
            raise SystemExit(f"SaProt returned {per_residue.shape[1]} residue vectors for "
                             f"{len(saprot_seq) // 2} residues - the window was truncated")
        return model.target_projector(per_residue).numpy()


def cosine(target_emb, drug_emb):
    """Ranking score, matching ultrafast/compute_topk.py."""
    t = target_emb.reshape(-1)
    d = drug_emb.reshape(drug_emb.shape[0], -1)
    return (d @ t) / (np.linalg.norm(d, axis=1) * np.linalg.norm(t) + 1e-12)


def main():
    os.makedirs(WORK, exist_ok=True)
    panel = load_panel()
    print(f"panel: {len(panel)} compounds")
    print(panel.groupby("group").size().to_string(), "\n")

    if not os.path.exists(CHECKPOINT):
        print("Downloading the SPRINT Lit-PCBA checkpoint ...")
        run(["gdown", CHECKPOINT_GDRIVE_ID, "-O", CHECKPOINT])

    pocket = pocket_residues()
    start, end = pocket_window(pocket)
    print(f"binding site: {len(pocket)} residues within {POCKET_CUTOFF} A of silybin, "
          f"spanning {min(pocket)}-{max(pocket)}")
    print(f"informed window: {start}-{end} ({end - start + 1} residues), "
          f"margins {min(pocket) - start} N / {end - max(pocket)} C\n")

    print("Building the structure-aware sequence for all of CpABC1 ...")
    t0 = time.perf_counter()
    full = saprot_sequence()
    t_foldseek = time.perf_counter() - t0

    cuts = [
        # what SPRINT does unaided: residues 1-1023, losing pocket residue 1101
        ("default", "default (residues 1-1023)", 1, 1023),
        # the informed cut, centred on the site
        ("pocket", f"pocket-centred ({start}-{end})", start, end),
    ]
    for _, label, lo, hi in cuts:
        kept = [r for r in pocket if lo <= r <= hi]
        lost = [r for r in pocket if not lo <= r <= hi]
        print(f"  {label}: {hi - lo + 1} residues, "
              f"{len(kept)}/{len(pocket)} pocket residues retained"
              + (f", losing {lost}" if lost else ""))

    print("\nLoading the SPRINT model ...")
    model = load_model()

    print(f"Embedding {len(panel)} ligands ...")
    t0 = time.perf_counter()
    drug_emb = embed_drugs(model, panel["smiles"].tolist())
    t_ligand = time.perf_counter() - t0
    print(f"  ligands embedded in {t_ligand:.1f} s, shape {drug_emb.shape}")
    if drug_emb.shape[0] != len(panel):
        raise SystemExit(f"got {drug_emb.shape[0]} ligand embeddings for {len(panel)} "
                         "compounds, so the mapping is unsafe")

    verdicts = {}
    for tag, label, lo, hi in cuts:
        seq = slice_saprot(full, lo, hi)
        print(f"\nEmbedding the protein, cut = {label} ...")
        t0 = time.perf_counter()
        target_emb = embed_target(model, seq)
        t_protein = time.perf_counter() - t0
        print(f"  protein embedded in {t_protein:.1f} s, shape {target_emb.shape}")

        scores = cosine(target_emb, drug_emb)
        result = evaluate(dict(zip(panel["name"], scores)))
        verdicts[label] = (report(f"SPRINT [{label}]", result), result["auc"], t_protein)
        result["panel"].to_csv(os.path.join(WORK, f"sprint_cpabc1_scores_{tag}.csv"),
                               index=False)

    print("\n" + "=" * 92)
    print("Which cut of the protein, and did either pass?")
    print("=" * 92)
    for label, (ok, auc, t_protein) in verdicts.items():
        print(f"  {label:34s} AUC {auc:.3f}   protein embed {t_protein:5.1f} s   "
              f"{'PASS' if ok else 'FAIL'}")
    print(f"\nfoldseek      {t_foldseek:7.1f} s   (once per structure)")
    print(f"ligand embed  {t_ligand:7.1f} s   ({t_ligand / len(panel):.3f} s/ligand)")
    print(f"peak memory   {peak_gb():7.1f} GB")
    print("=" * 92)
    return 0 if any(ok for ok, _, _ in verdicts.values()) else 1


if __name__ == "__main__":
    sys.exit(main())
